blogs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
]

photos/urls.py
from django.conf.urls import url
from .views import DeleteView,PhotoView

app_name='photos'
urlpatterns = [
url('^flicker/', PhotoView.as_view(), name="flicker"),
url('^delete/(?P<id>\d+)/$', DeleteView, name="delete")
]

picha/urls.py
from django.conf.urls import include, url,static
from django.contrib import admin
from django.views.generic.base import TemplateView
from feedback.views import FeedbackView
from weather.views import weather_view
from users.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', home_view, name="home"),
    url(r'^feedback', FeedbackView.as_view(), name="feedback"),
    url(r'^admin', admin.site.urls),
    url('users/', include('users.urls')),
    url('users/', include('django.contrib.auth.urls')),
    url(r'^photos/', include('photos.urls')),
    url(r'^weather/', include('weather.urls')),
    url(r'^blogs/', include('blogs.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weather/urls.py
from django.conf.urls import url
from . import views

app_name='weather'
urlpatterns = [
url('^$', views.weather_view, name="weather"),
url('^delete/(?P<city>[-\w]+)/$', views.delete_view, name="delete")
]
# url(r'^delete/(?P<city>[-\w]+)/$', views.delete_view, name="delete")

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css"  media="screen,projection"/>
    <!--Let browser know website is optimized for mobile-->
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.7/angular.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog_post.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <link rel="icon" type="image/png" href="{% static 'images/iconn.png' %}">
    <title>{% block title %}Picha!{% endblock %}</title>
    {% block headcss %}{% endblock %}
  </head>
  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'home' %}"><strong>Gajanan</strong></a>
          </div>
            <ul class="nav navbar-nav">
              <li class="nav-item"><a href="{% url 'photos:flicker' %}">Flicker</a></li>
              <li class="nav-item"><a href="{% url 'weather:weather' %}">Weather</a></li>
              <li class="nav-item"><a href="{% url 'post_list' %}">Blog</a></li>
              <li class="nav-item dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Options<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'profile' %}">Profile</a></li>
                  <li><a href="{% url 'marks' %}">Marks</a></li>
                  <li><a href="{% url 'chat' %}">Google Charts</a></li>
                  <li><a href="{% url 'results' %}">Results</a></li>
                  <li><a href="{% url 'chartjs' %}">ChartJS</a></li>
                  <li><a href="{% url 'eye' %}">Eye</a></li>
                </ul>
              </li>
            </ul>
          
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'feedback' %}"><span class="glyphicon glyphicon-envelope"></span> FeedBack</a></li>
              <li><a href="{% url 'signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
              <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> LogIn</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> LogOut</a></li>
              {% endif %}
            </ul>

        </div>
      </nav>
    </div>
      <div class="container-fluid">
        {% block content %}{% endblock %}
      </div>
      <footer>
        <div class="container">
          <p style="color:red; text-align:center">&copy;gajananpatra.com</p>
        </div>
      </footer>
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="//code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://code.iconify.design/1/1.0.0-rc6/iconify.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    {% block extrabody %}{% endblock %}
  </body>
</html>